export const INITIALIZE_APPLICATION = 'INITIALIZE_APPLICATION';
export const SET_CIRCUIT_STATE = 'SET_CIRCUIT_STATE';
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
export const OPEN_WIRE_SEGMENT_TOOLTIP = 'OPEN_WIRE_SEGMENT_TOOLTIP';
export const CLOSE_WIRE_SEGMENT_TOOLTIP = 'CLOSE_WIRE_SEGMENT_TOOLTIP';
export const OPEN_GATE_TOOLTIP = 'OPEN_GATE_TOOLTIP';
export const CLOSE_GATE_TOOLTIP = 'CLOSE_GATE_TOOLTIP';
